server:
  port: 8311
spring:
  application:
    name: redisson
#logging:
#  level:
#    org.redisson.*.*: trace
#    org.redisson.client.handler.CommandEncoder: info
#    org.redisson.client.handler.CommandDecoder: info
#    org.redisson.client.handler.PingConnectionHandler: info
#    org.redisson.client.handler.CommandPubSubDecoder: info
#    io.netty.*.*: trace
