spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 600000
            read-timeout: 600000
          postgresClient:
            url: "http://127.0.0.1:8080/v1/accounts"
          postgresReckonerClient:
            url: "http://127.0.0.1:8080/v1/reckoner"
          mongo-client:
            url: "http://127.0.0.1:8222/v1/account-update-record"
    config:
      name: data-postgre
  config:
    import: configserver:http://127.0.0.1:9222
  devtools:
    restart:
      enabled: false
feign:
  circuitbreaker:
    enabled: true