spring:
  config:
    import: configserver:http://config-service:80
  datasource:
    url: jdbc:postgresql://${postgre-url:192.168.205.1:5433}/postgres
  data:
    redis:
      cluster:
        nodes:
          - "redis-cluster-0.redis-cluster.default.svc.cluster.local:6379"
          - "redis-cluster-1.redis-cluster.default.svc.cluster.local:6379"
          - "redis-cluster-2.redis-cluster.default.svc.cluster.local:6379"
          - "redis-cluster-3.redis-cluster.default.svc.cluster.local:6379"
          - "redis-cluster-4.redis-cluster.default.svc.cluster.local:6379"
          - "redis-cluster-5.redis-cluster.default.svc.cluster.local:6379"
