spring:
  mvc:
    log-resolved-exception: true
  config:
    import: configserver:http://127.0.0.1:9333
  devtools:
    restart:
      enabled: false
  cloud:
    config:
      name: data-postgre
    openfeign:
      client:
        config:
          default:
            connect-timeout: 600000
            read-timeout: 600000
          redisson-client:
            url: "http://127.0.0.1:8311"
          mongo-acct-blc-client:
            url: "http://127.0.0.1:8222/accts_balance_adjust/v1"
          mongo-client:
            url: "http://127.0.0.1:8222/v1/account-update-record"

  task:
    scheduling:
      thread-name-prefix: reckoner-acc-
      pool:
        size: 5
server:
  error:
    include-stacktrace: always