spring:
  config:
    import: configserver:http://127.0.0.1:9333
  devtools:
    restart:
      enabled: false
  cloud:
    config:
      name: data-postgre
    openfeign:
      client:
        config:
          default:
            connect-timeout: 600000
            read-timeout: 600000
          redisson-client:
            url: "http://127.0.0.1:8311"
  task:
    scheduling:
      thread-name-prefix: reckoner-acc-
      pool:
        size: 5