server:
  port: 6722
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
logging:
  level:
#    root: trace
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: debug
    reactor.netty: debug


